language: ruby
rvm:
- 2.3.0
env:
- DB=postgresql
addons:
  postgresql: '9.3'
before_install: gem update bundler rake
before_script:
- rake db:setup
script:
- RAILS_ENV=test COVERAGE=true bundle exec rake --trace db:migrate spec
cache: bundler
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/04f07b2eeecfad3cf278
    on_success: change
  email:
    recipients:
    - justin.schulz@gmail.com
    - jasnow@hotmail.com
    on_success: change
    on_failure: always
sudo: false
deploy:
  provider: heroku
  api_key:
    secure: juG26bMWtVPA4hV5/3TGd3Otgfmanam17fSX+BQJuRUgqDuD9kD3tvwsKuf+DKIpuYE89Ull0MwYoqwfkgEQWJ1hdUcsaVKxeTuxpstGhg3jWwnMX1tafQxrdtqCGsZ2yD9Jc+pogWSwwFHutCC0KFvli9uM268RLqJD9MEKEcjWNGw4j6Cer02PGZL65ZB76XAeb+r8j5frxTksWmNEl3XjId+Gk3xiSsIgJmKVwGZuUo2nPh5HjEYgpAmwnmi9DsLaeFdIZiNXn66E7HETRF15+93Hvw/vGj6yvludtV9cBvINmtC1EJVRJlNWZAFF75nDB+htZiFV7ZzKU4sgEsmhxe7+J+Ksory5tMZdlUDfox7Remn8lvlmz+dV95cFIainzdAaYKBIT+sy1ZkzKv03+eTUq/ngMW8EcNbuztOWZkZFygGnKWSeozPiedb0tsGgtbs7tolTWR9JULFm9LbwiAqaxdT+szF5NE8JEw+VnpRApJ/Hh/C+6esmbMAHRksI9vq3eT5hK2yS47kL+QW9Q/ZzAkNUASYq08E+Y627mnfy//5M+HukU/XOzkPj7jVBoB3XG5aWVGcEKkiFaEx5ThpgqMDxO7NAJr9k0k7pDNCAvuxCgNI8q+jnMAM1NCGeo4vTk4od3JyIVZk+TAN8Iv/pludnZpdJq6NT8po=
  app: bbnb-staging
  skip_cleanup: true
  on:
    repo: SandersForPresident/BernieBNB
