language: ruby
rvm:
- 2.2.3
env:
- DB=postgresql
addons:
  postgresql: '9.3'
before_install: gem update bundler rake
before_script:
- bundle exec rake db:setup
script:
- RAILS_ENV=test COVERAGE=true bundle exec rake --trace db:migrate spec
cache: bundler
notifications:
  webhooks:
    on_success: change
  email:
    recipients:
    - dsjoerg@gmail.com
    on_success: change
    on_failure: always
sudo: false
