version: '2'
services:
  db:
    image: postgres
  web:
    build: .
    restart: always
    command: bash -c "rm -f /myapp/tmp/pids/server.pid && bundle exec rake db:migrate && bundle exec rake db:setup && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
